dist: trusty
sudo: required
language: bash

before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh | bash
notifications:
  slack:
    rooms:
      secure:
dBrw7bFhMEzbmfoROReLbkz5awdOvGoX3/G/K0/7RQwJqtxSWi1PUzSC2VbnHS7IEw6P8LZWZeK4u8SvKyyh/C0nJ7f0/AmDRA2XtEUtr5MtIjm6i18MOc+hWQ7QleaVd9UzFlLumru+BXaAitnwsW5etQFe5rJFy/p8OnTgDpslz19acIwRjaytq3Ks/nK4Ko1QSMudxUv+NfBA54hOj+J7Rgh9mxdAGFKhorNYBE8zLgFKTv8sBRUMvGa2c5HxW40tnIqodeyYYIZ0O4NYitKVfC/yLGqnlmR8sNwZfc+pTRvPIoGOC3wo2dtV3sFsNTLZQMFoVFgd2TrOExbZg+29JPSozSa0QfBhUoNNOP37W+OdaN+vd2zVn19nRcgDnoqY0a4x7TdjEg8W1OoTympCLzyxnw/WrylEMtNKmsU+lUy1tUj+5z+WXbCO2lriK2ewkSWo4UE0CXHPm90UAaZqVXqFwztMfx4uU7QMFHUCwETRgCF3lW55DSNPQ25oCs+abWcnp7uQerX1EEBVFrSvuEG7bKcvW6NezUgimPXZodBR3CcS1r98LBIPRg88jNhetDoKDlnS57VbUUL5AoOH6FRCIpkSilvM5UOtW4dtbPkp4PkD3EcMjNVIuc72UtV971iM06GJSRSbP+35Yui9lWqXvvzGl54D8AJLH2I=
